version: "3.7"

services:
  #Laravel App
  app:
    container_name: lencana
    build:
      context: .
      dockerfile: Dockerfile
    image: lencana-apps
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/laravel_docker
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/laravel_docker
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
    networks:
      - mynet

  #Nginx Service
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "5555:80"
  #     - "443:443"
  #   volumes:
  #     - ./:/var/www/html
  #     - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
  #   networks:
  #     - mynet

  # PHMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: project_phpmyadmin
    ports:
      - 8182:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpasswordmysql
    restart: always
    depends_on:
      - db
    networks:
      - mynet

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3400:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpasswordmysql
    #    command: --init-file /data/application/init.sql
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./db_lencana.sql:/data/application/init.sql
    networks:
      - mynet

#Docker Networks
networks:
  mynet:
    driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local
